name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  print-matrix-value:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name for template A
        run: echo The username is ${{ inputs.username }}